### ISSUE TITLE
Rmarkdown chapter / open-code

### ISSUE THREAD

**Issue by DorienHuijser** [eur-synclab/eur-synclab.github.io#50]
In open science > reproducibility > open-code.md

- RMarkdown: short how-to or link to existing tutorials + examples 
- perhaps combine with Binder, Docker?

**Comment by eduardklap** [comment]
will make a start with this chapter

**Comment by eduardklap** [comment]
first draft RMarkdown online
Next step: some info on Jupyter notebooks
